from enum import Enum


class ReservationStatusEnum(str, Enum):
    PENDING_PAYMENT = "PENDING_PAYMENT"
    PENDING_PASTORAL_LETTER = "PENDING_PASTORAL_LETTER"
    PENDING_BOTH = "PENDING_BOTH"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"
    EXPIRED = "EXPIRED"
